# Generated by Django 6.0.4 on 2026-04-14 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_client', models.CharField(max_length=50, unique=True, verbose_name='Numéro client')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du client')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['num_client'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_produit', models.CharField(max_length=50, unique=True, verbose_name='Numéro produit')),
                ('design', models.CharField(max_length=255, verbose_name='Désignation')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['num_produit'],
            },
        ),
        migrations.CreateModel(
            name='AuditVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('INSERT', 'Insertion'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression')], max_length=10, verbose_name="Type d'opération")),
                ('date_mise_a_jour', models.DateTimeField(auto_now_add=True, verbose_name='Date de mise à jour')),
                ('nom_client', models.CharField(max_length=255, verbose_name='Nom du client')),
                ('design_produit', models.CharField(max_length=255, verbose_name='Désignation du produit')),
                ('qtesortie_ancien', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ancienne quantité sortie')),
                ('qtesortie_nouv', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nouvelle quantité sortie')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Audit de vente',
                'verbose_name_plural': 'Audit des ventes',
                'ordering': ['-date_mise_a_jour'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_sortie', models.PositiveIntegerField(verbose_name='Quantité sortie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='ventes.client', verbose_name='Client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='ventes.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('qte_sortie__gt', 0)), name='vente_qte_sortie_gt_0')],
            },
        ),
    ]
